name: Build and Push Container Image

on:
  schedule:
    - cron: 0 1 */14 * 0
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfiles/bunjs.dockerfile
            runtime: bunjs
          - dockerfile: ./Dockerfiles/nodejs-lts.dockerfile
            runtime: nodejs-lts
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.runtime }}:latest'
          platforms: 'linux/amd64,linux/arm64'
