name: Cleanup GH Container Registry

on:
    schedule:
        - cron: 0 6 28-31 * *
    workflow_dispatch:

jobs:
  house-keeping-nodejs-lts:
    runs-on: ubuntu-latest
    steps:
      - name: Keep the latest 5 versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'devcontainers/nodejs-lts'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.NUKE_TOKEN }}
      - name: Keep the latest 5 versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'devcontainers/bunjs'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.NUKE_TOKEN }}
